name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build API Docker image
        run: docker build -t pedimeapp-api ./src/api

      - name: Build Listener Docker image
        run: docker build -t pedimeapp-listener ./src/listener

      - name: Run API unit tests
        run: |
          cd src/api
          go test ./...

      - name: Run Listener unit tests
        run: |
          cd src/listener
          go test ./...

      - name: Run Shared unit tests
        run: |
          cd src/shared
          go test ./...
